# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  host: localhost
  database: dbdevelopment
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  database: dbtest
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  database: dbproduction
  pool: 5
  timeout: 5000
